演習問題1

In [3]:
import pandas as pd
health_data=pd.read_excel("健康診断.xlsx")
health_data

     年齢     血圧     肺活量   性別  疾患の有無    体重
0  30.0  102.0  4100.0  1.0    1.0  81.0
1  44.0  122.0  4250.0  NaN    0.0  60.0
2   NaN  104.0     NaN  1.0    0.0   NaN
3  25.0    NaN  3000.0  0.0    NaN  42.0
4  27.0  110.0  4800.0  1.0    0.0  75.0

演習問題2

In [8]:
print("年齢の平均値:",health_data["年齢"].mean())
print("血圧の平均値:",health_data["血圧"].mean())
print("肺活量の平均値:",health_data["肺活量"].mean())
print("体重の平均値:",health_data["体重"].mean())

年齢の平均値: 31.5
血圧の平均値: 109.5
肺活量の平均値: 4037.5
体重の平均値: 64.5

演習問題3

In [12]:
health_data["性別"].mode()

0    1.0
Name: 性別, dtype: float64

In [13]:
health_data["疾患の有無"].mode()

0    0.0
Name: 疾患の有無, dtype: float64

演習問題4

In [15]:
health_data["年齢"]=health_data["年齢"].fillna(31)
health_data["血圧"]=health_data["血圧"].fillna(109)
health_data["肺活量"]=health_data["肺活量"].fillna(4037)
health_data["性別"]=health_data["性別"].fillna(1)
health_data["疾患の有無"]=health_data["疾患の有無"].fillna(0)
health_data["体重"]=health_data["体重"].fillna(64)
health_data

     年齢     血圧     肺活量   性別  疾患の有無    体重
0  30.0  102.0  4100.0  1.0    1.0  81.0
1  44.0  122.0  4250.0  1.0    0.0  60.0
2  32.0  104.0  4038.0  1.0    0.0  64.0
3  25.0  110.0  3000.0  0.0    0.0  42.0
4  27.0  110.0  4800.0  1.0    0.0  75.0