データ加工の技術

In [5]:
import pandas as pd
customer = pd.read_excel("顧客情報.xlsx")
customer

        顧客番号  顧客氏名            顧客住所        顧客電話番号          顧客メールアドレス
0  customer1  田中太郎    山口県山口市滝町1番1号  083-922-3111  tanaka@sample.com
1  customer2  山田花子  青森県青森市長島一丁目1-1  017-722-1111  yamada@sample.com

In [9]:
item = pd.read_excel("商品情報.xlsx")
item

    商品番号   商品名   単価 仕入れ先
0  item1    パン  100  A食品
1  item2  コーヒー  120  B飲料
2  item3   サラダ  200  C農園
3  item4  おにぎり  150  D食品

In [10]:
transaction_4 = pd.read_excel("4月販売情報.xlsx")
transaction_4

           販売番号        販売日   商品番号       顧客番号
0  transaction1 2021-04-01  item1  customer1
1  transaction2 2021-04-02  item2  customer2
2  transaction3 2021-04-03  item3  customer1

In [11]:
transaction_5 = pd.read_excel("5月販売情報.xlsx")
transaction_5

           販売番号        販売日   商品番号       顧客番号
0  transaction4 2021-05-01  item3  customer2
1  transaction5 2021-05-02  item4  customer1
2  transaction6 2021-05-03  item4  customer2

In [12]:
transaction = pd.concat([transaction_4, transaction_5], ignore_index=True)
transaction

           販売番号        販売日   商品番号       顧客番号
0  transaction1 2021-04-01  item1  customer1
1  transaction2 2021-04-02  item2  customer2
2  transaction3 2021-04-03  item3  customer1
3  transaction4 2021-05-01  item3  customer2
4  transaction5 2021-05-02  item4  customer1
5  transaction6 2021-05-03  item4  customer2

商品番号をもとにtransactionとitemを横に結合(JOIN)する

In [14]:
join_data = pd.merge(transaction, item, on="商品番号")
join_data

           販売番号        販売日   商品番号       顧客番号   商品名   単価 仕入れ先
0  transaction1 2021-04-01  item1  customer1    パン  100  A食品
1  transaction2 2021-04-02  item2  customer2  コーヒー  120  B飲料
2  transaction3 2021-04-03  item3  customer1   サラダ  200  C農園
3  transaction4 2021-05-01  item3  customer2   サラダ  200  C農園
4  transaction5 2021-05-02  item4  customer1  おにぎり  150  D食品
5  transaction6 2021-05-03  item4  customer2  おにぎり  150  D食品

In [15]:
join_data = pd.merge(join_data, customer, on="顧客番号")
join_data = join_data.sort_values('販売日', ascending=True)
join_data = join_data.reset_index(drop=True)
join_data

,販売番号,販売日,商品番号,顧客番号,商品名,単価,仕入れ先,顧客氏名,顧客住所,顧客電話番号,顧客メールアドレス
0,transaction1,2021-04-01,item1,customer1,パン,100,A食品,田中太郎,山口県山口市滝町1番1号,083-922-3111,tanaka@sample.com
1,transaction2,2021-04-02,item2,customer2,コーヒー,120,B飲料,山田花子,青森県青森市長島一丁目1-1,017-722-1111,yamada@sample.com
2,transaction3,2021-04-03,item3,customer1,サラダ,200,C農園,田中太郎,山口県山口市滝町1番1号,083-922-3111,tanaka@sample.com
3,transaction4,2021-05-01,item3,customer2,サラダ,200,C農園,山田花子,青森県青森市長島一丁目1-1,017-722-1111,yamada@sample.com
4,transaction5,2021-05-02,item4,customer1,おにぎり,150,D食品,田中太郎,山口県山口市滝町1番1号,083-922-3111,tanaka@sample.com
5,transaction6,2021-05-03,item4,customer2,おにぎり,150,D食品,山田花子,青森県青森市長島一丁目1-1,017-722-1111,yamada@sample.com

データクレンジング

In [16]:
uriage_data = pd.read_excel("クレンジング前.xlsx")
uriage_data

          日付   曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01    木   ノート  100   1    男性   24.0
1 2021-04-02    金    鉛筆   80   5    女性   16.0
2 2021-04-03    土  マジック  200   1    男性   15.0
3 2021-04-04  NaN  マジック  200   2    女性    9.0
4 2021-04-05    月   ノート  100   2    女性    NaN
5 2021-04-06    火   ハサミ  400   1   NaN   14.0
6 2021-04-07    水   はさみ  400   2    女性   19.0

In [17]:
uriage_data.loc[3, "曜日"] = "日"
uriage_data

          日付 曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01  木   ノート  100   1    男性   24.0
1 2021-04-02  金    鉛筆   80   5    女性   16.0
2 2021-04-03  土  マジック  200   1    男性   15.0
3 2021-04-04  日  マジック  200   2    女性    9.0
4 2021-04-05  月   ノート  100   2    女性    NaN
5 2021-04-06  火   ハサミ  400   1   NaN   14.0
6 2021-04-07  水   はさみ  400   2    女性   19.0

In [18]:
uriage_data["商品名"] = uriage_data["商品名"].str.replace("はさみ", "ハサミ")
uriage_data

          日付 曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01  木   ノート  100   1    男性   24.0
1 2021-04-02  金    鉛筆   80   5    女性   16.0
2 2021-04-03  土  マジック  200   1    男性   15.0
3 2021-04-04  日  マジック  200   2    女性    9.0
4 2021-04-05  月   ノート  100   2    女性    NaN
5 2021-04-06  火   ハサミ  400   1   NaN   14.0
6 2021-04-07  水   ハサミ  400   2    女性   19.0

In [20]:
uriage_data["顧客の性別"].mode()
# modeはそのデータの指定された属性の最頻値(最もよく出てくる値)を指している。
#(今回は性別という属性において男よりも女性の方が多かった)

0    女性
Name: 顧客の性別, dtype: object

In [21]:
uriage_data["顧客の性別"] = uriage_data["顧客の性別"].fillna("女性")
uriage_data

          日付 曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01  木   ノート  100   1    男性   24.0
1 2021-04-02  金    鉛筆   80   5    女性   16.0
2 2021-04-03  土  マジック  200   1    男性   15.0
3 2021-04-04  日  マジック  200   2    女性    9.0
4 2021-04-05  月   ノート  100   2    女性    NaN
5 2021-04-06  火   ハサミ  400   1    女性   14.0
6 2021-04-07  水   ハサミ  400   2    女性   19.0

In [22]:
uriage_data["顧客の年齢"].mean()
# meanはデータの中の平均値

16.166666666666668

In [23]:
uriage_data["顧客の年齢"]=uriage_data["顧客の年齢"].fillna(16)
uriage_data

          日付 曜日   商品名   価格  個数 顧客の性別  顧客の年齢
0 2021-04-01  木   ノート  100   1    男性   24.0
1 2021-04-02  金    鉛筆   80   5    女性   16.0
2 2021-04-03  土  マジック  200   1    男性   15.0
3 2021-04-04  日  マジック  200   2    女性    9.0
4 2021-04-05  月   ノート  100   2    女性   16.0
5 2021-04-06  火   ハサミ  400   1    女性   14.0
6 2021-04-07  水   ハサミ  400   2    女性   19.0